/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientapp_rental;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class FormChat extends javax.swing.JFrame implements Runnable {

    String hasil = "";
    Thread t;
    Socket clientSocket;
    BufferedReader chatFromServer;
    DataOutputStream sendToServer;

    /**
     * Creates new form FormChat
     */
    public FormChat(Socket _socket, String _username) {
        initComponents();
        setLocationRelativeTo(null); //Membuat form berada di tengah

        if (_username == null) {
            System.exit(0);
        }

        txtNama.setText(_username);
        clientSocket = _socket;

        if (t == null) {
            t = new Thread(this, "Client Thread");
            t.start();
        }
    }

    private FormChat() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void run() {
        while (true) {
            getMessage();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtPesan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtChat = new javax.swing.JTextArea();
        btnHistoryChat = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        btnPanduan = new javax.swing.JButton();
        btnCall = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(675, 614));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setText("Chat Client");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Username");

        txtNama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNama.setEnabled(false);

        txtPesan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Pesan");

        txtChat.setEditable(false);
        txtChat.setColumns(20);
        txtChat.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        txtChat.setRows(5);
        jScrollPane1.setViewportView(txtChat);

        btnHistoryChat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnHistoryChat.setText("History Chat");
        btnHistoryChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryChatActionPerformed(evt);
            }
        });

        btnSend.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnPanduan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPanduan.setText("Panduan");
        btnPanduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanduanActionPerformed(evt);
            }
        });

        btnCall.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btnCall.setText("Hubungi Admin");
        btnCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtPesan)))
                        .addGap(18, 18, 18)
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPanduan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(102, 102, 102)
                        .addComponent(btnCall))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHistoryChat)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCall)
                            .addComponent(btnPanduan)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSend))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHistoryChat)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void getMessage() {
        try {
            chatFromServer = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
            String chatServer = chatFromServer.readLine();
            hasil = chatServer;
            String[] splitted = chatServer.split("&");
            if (chatServer.contains("%cekListRumah%")) {
                for (int i = 0; i < splitted.length - 1; i++) {
                    String[] listInfo = splitted[i].split(";");
                    txtChat.append(listInfo[0] + ", Alamat : " + listInfo[1] + ", Harga Per Hari : Rp." + listInfo[2] + "\n");
                }
            } else if (chatServer.contains("showChat&&")) {
                FormShowClient formShow = new FormShowClient(hasil);
                formShow.setVisible(true);
            } else {
                txtChat.append(chatServer + "\n");
            }

        } catch (IOException ex) {
            Logger.getLogger(FormChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void sendChat(String msg) {
        try {
            sendToServer = new DataOutputStream(clientSocket.getOutputStream());
            sendToServer.writeBytes(msg + "\n");
        } catch (IOException ex) {
            Logger.getLogger(FormChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnHistoryChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryChatActionPerformed
        try {
            DataOutputStream msgToServer = new DataOutputStream(clientSocket.getOutputStream());

            msgToServer.writeBytes("showchatclient;-" + txtNama.getText() + "\n");
        } catch (IOException ex) {
            Logger.getLogger(FormShowClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHistoryChatActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        try {
            String chatClient, chatNama;

            chatClient = txtPesan.getText();
            chatNama = txtNama.getText();

            if (chatClient.contains("cek tanggal:")) {
                String hasil[] = chatClient.split(":");
                sendChat("cek tanggal;-" + hasil[1] + ";-" + hasil[2]);
            } else if (chatClient.contains("reservasi:")) {
                String hasil[] = chatClient.split(":");
                sendChat("reservasi;-" + hasil[1] + ";-" + txtNama.getText() + ";-" + hasil[2]);
            } else if (chatClient.contains("lacak:")) {
                String hasil[] = chatClient.split(":");
                sendChat("lacak;-" + hasil[1] + ";-" + txtNama.getText());
            } else if (chatClient.equals("cek list rumah")) {
                sendChat("cek list rumah");
            } else {
                sendChat(chatNama + ":" + chatClient);
            }
            txtChat.append(chatNama + ": " + chatClient + "\n");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnPanduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanduanActionPerformed
        JOptionPane.showMessageDialog(this, "1. Untuk mengecek ketersediaan tanggal untuk reservasi, ketik: "
                + "'cek tanggal:<tanggal masuk> sampai <tanggal keluar>:<nama rumah>'"
                + "\n     Contoh: 'cek tanggal:2021-10-12 sampai 2021-12-12:Rumah A'"
                + "\n2. Untuk melakukan reservasi, ketik: 'reservasi:<tanggal masuk> sampai <tanggal keluar>:<nama rumah>'"
                + "\n     Contoh: 'reservasi:2021-10-12 sampai 2021-12-12:Rumah A'"
                + "\n3. Untuk melacak reservasi Anda, ketik: 'lacak:<tanggal masuk> sampai <tanggal keluar>'"
                + "\n     Contoh: 'lacak:2021-10-12 sampai 2021-12-12'"
                + "\n4. Untuk melihat list rumah yang tersedia, ketik: 'cek list rumah'"
                + "\n*Jika Anda bingung dalam melakukan reservasi, Anda dapat menghubungi Admin."
                + "\nNote: Penulisan tanggal dengan format: yyyy-MM-dd.", "Panduan", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnPanduanActionPerformed

    private void btnCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCallActionPerformed
        FormCallClient formCallCallClient = new FormCallClient();
        formCallCallClient.setVisible(true);
    }//GEN-LAST:event_btnCallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCall;
    private javax.swing.JButton btnHistoryChat;
    private javax.swing.JButton btnPanduan;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtChat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPesan;
    // End of variables declaration//GEN-END:variables
}
